#!/bin/sh
#$ -cwd
#$ -l {NODE}={N_NODES}
#$ -l h_rt={H_RT}
#$ -N d_{EXEC}
#$ -o output_files/mpi/{EXEC}.{JOB}
#$ -e error_files/mpi/{EXEC}.{JOB}

. /etc/profile.d/modules.sh
module load cuda/8.0.61
module load openmpi/2.1.2

export OMP_NUM_THREADS={N_THREADS}

mpirun -npernode 1 -n {N_NODES} -bind-to none -x LD_LIBRARY_PATH \
    ./{EXEC} {N_STEPS} {NX} {NY}

